import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
   children,
   user,
   team,
   params
}: {
  children: React.ReactNode
  user: React.ReactNode
  team: React.ReactNode
  params: {
    lang: string
  }
}) {
    console.log(params.lang)
    let page = team
    if(params.lang == 'ko'){
        page = user
    }

  return (
      <section>{children}{page}</section>
  )
}
